FROM node:latest

WORKDIR /app

COPY ./prisma .

RUN yarn

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait

RUN chmod +x /wait

CMD /wait && \
  yarn deploy && \
  yarn generate && \
  yarn start